---

- name: run on localhost
  hosts: localhost
  become: yes
  tasks:

  - name: Update repositories cache
    apt:
      update_cache: yes

  - name: Upgrade repository
    command: apt upgrade -y

  - name: Upgrade repository
    command: apt autoremove

  - name: install git
    apt: 
      name: git
